services:
  blog:
    build: .
    container_name: fasthtml_blog
    ports:
      - 8000:8000
    environment:
      MONGO_URL: mongodb://root:ju0eiXoo@mongo:27017/

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ju0eiXoo
    volumes:
      - blog_database:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ju0eiXoo
      ME_CONFIG_MONGODB_URL: mongodb://root:ju0eiXoo@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    

volumes:
  blog_database: {}